package bitkub

import "github.com/rs/zerolog"

var ErrorCode = map[int]string{
	0:   "No error",
	1:   "Invalid JSON payload",
	2:   "Missing X-BTK-APIKEY",
	3:   "Invalid API key",
	4:   "API pending for activation",
	5:   "IP not allowed",
	6:   "Missing / invalid signature",
	7:   "Missing timestamp",
	8:   "Invalid timestamp",
	9:   "Invalid user",
	10:  "Invalid parameter",
	11:  "Invalid symbol",
	12:  "Invalid amount",
	13:  "Invalid rate",
	14:  "Improper rate",
	15:  "Amount too low",
	16:  "Failed to get balance",
	17:  "Wallet is empty",
	18:  "Insufficient balance",
	19:  "Failed to insert order into db",
	20:  "Failed to deduct balance",
	21:  "Invalid order for cancellation (Unable to find OrderID or Symbol.)",
	22:  "Invalid side",
	23:  "Failed to update order status",
	24:  "Invalid order for lookup",
	25:  "KYC level 1 is required to proceed",
	30:  "Limit exceeds",
	40:  "Pending withdrawal exists",
	41:  "Invalid currency for withdrawal",
	42:  "Address is not in whitelist",
	43:  "Failed to deduct crypto",
	44:  "Failed to create withdrawal record",
	45:  "Nonce has to be numeric",
	46:  "Invalid nonce",
	47:  "Withdrawal limit exceeds",
	48:  "Invalid bank account",
	49:  "Bank limit exceeds",
	50:  "Pending withdrawal exists",
	51:  "Withdrawal is under maintenance",
	52:  "Invalid permission",
	53:  "Invalid internal address",
	54:  "Address has been deprecated",
	55:  "Cancel only mode",
	56:  "User has been suspended from purchasing",
	57:  "User has been suspended from selling",
	90:  "Server error (please contact support)",
	400: "400 Bad Request",
	401: "401 Unauthorized",
	405: "405 Method not Allow",
}

var ErrorCodeV4 = map[string]string{
	"B1000-CW": "User account is suspended",
	"B1001-CW": "Network is disabled",
	"B1002-CW": "CWS Wallet not found",
	"B1003-CW": "Insufficient balance",
	"B1004-CW": "User mismatch condition",
	"B1005-CW": "Duplicate key",
	"B1006-CW": "Airdrop already transfer",
	"B1007-CW": "Symbol required",
	"B1008-CW": "Event Symbol mismatched",
	"B1009-CW": "Pending withdrawal exists",
	"B1010-CW": "User account is frozen",
	"B1011-CW": "Withdrawal exceeds daily limit",
	"B1012-CW": "Address is not trusted",
	"B1013-CW": "Withdrawal is frozen",
	"B1014-CW": "Address is not whitelisted",
	"B1015-CW": "Request is processing",
	"B1016-CW": "Deposit is frozen",
	"V1000-CW": "User not found",
	"V1001-CW": "Asset not found",
	"V1002-CW": "Event not found",
	"V1003-CW": "Invalid signature",
	"V1004-CW": "Signature has expired",
	"V1005-CW": "Transaction not found",
	"V1006-CW": "Invalid parameter",
	"V1007-CW": "Symbol not found",
	"V1008-CW": "Address not yet generated for this symbol",
	"V1009-CW": "Memo not found for this address",
	"V1010-CW": "Address not found",
	"V1011-CW": "Address already exists",
	"V1012-CW": "Destination address not active",
	"V1015-CW": "Coin not found",
	"A1000-CW": "Unauthorized Access",
	"A1001-CW": "Permission denied",
	"S1000-CW": "Internal service error",
}

func init() {
	zerolog.TimeFieldFormat = zerolog.TimeFormatUnix
}
